import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'

export default function Home({ newsResults }) {
  return ( <
    div >
      <Head>
        <title >Twitter clone </title>
        <meta name = "description"
        content = "Generated by create next app" />
        <link rel = "icon"
        href = "/favicon.ico" />
      </Head>

      <main className='flex min-h-screen mx-auto '>
        {
          /* Sidebar */ } 
          <Sidebar />

          {
            /* Feed */ }
            <Feed />

        {
          /* Widgets */ }
          <Widgets newsResults={ newsResults.articles } />

        {
          /* Modals */ }
      </main>

      
    </div >
  )
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/fr.json

export async function getServerSideProps() {
    const newsResults = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/fr.json')
        .then((res) => res.json());

    console.log({ results: newsResults})

    return {
        props: {
            newsResults
        }
    }
}